root         2020-12-05 15:46:15,237 INFO     config.py:create_api API created
root         2020-12-05 15:46:15,249 INFO     bot.py:<module> Dorelle Jude Courtney
root         2020-12-05 15:46:26,522 INFO     config.py:create_api API created
root         2020-12-05 15:46:26,539 INFO     bot.py:<module> Illa Keligot
root         2020-12-05 15:49:21,986 INFO     config.py:create_api API created
root         2020-12-05 15:49:21,999 INFO     bot.py:<module> Georgianne Sibie
root         2020-12-05 15:49:44,061 INFO     config.py:create_api API created
root         2020-12-05 15:49:44,062 ERROR    names.py:getList Error opening file
Traceback (most recent call last):
  File "C:\Users\The Amazing Pip\Desktop\work\tw_bot\src\names.py", line 7, in getList
    f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'assets/first-namessd.txt'
error
